apiVersion: v1
kind: ConfigMap
metadata:
  name: dozuki-resources-configmap
data:
  memcached.json: |
    {
      "localCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      },
      "globalCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      },
      "testCluster": {
        "servers": [
          {
            "hostname": "{{ .Values.memcached.host }}",
            "port": 11211
          }
        ]
      }
    }
  aws-resources.json: |
    {
      "S3.enabled": true,
      "Ec2.enabled": true,
      "CloudFront.enabled": false,
      "LH.localFileSystem": false,
      "CdnUrls.alwaysRelative": false
    }
  s3.json: |
    {
      "region": "{{ .Values.aws.region }}",
      "encryptionKeyId": "{{ .Values.s3.kmsKey }}"
      {{- if .Values.minio.enabled }}
      ,"endpoint": "http://dozuki-minio.{{ .Release.Namespace }}.svc.cluster.local"
      {{- end }}
    }
  buckets.json: |
    {
      "default": {
        "guide-images": "{{ .Values.s3.imagesBucket }}",
        "guide-pdfs": "{{ .Values.s3.pdfsBucket }}",
        "documents": "{{ .Values.s3.documentsBucket }}",
        "guide-objects": "{{ .Values.s3.objectsBucket }}"
      }
    }
  common.json: |
    {
      "baseNanositeDomain": "{{ .Values.hostname }}"
    }
  sentry.json: |
    {
      "dsnPhp": "{{ .Values.sentry.dsn }}",
      "tags": {
        "deployment": "Private Cloud",
        "pc_environment": "{{ .Values.environment }}",
        "customer": "{{ .Values.customer }}",
        "aws_account": "{{ .Values.aws.accountId }}",
        "aws_region": "{{ .Values.aws.region }}",
        "kots_customer": "{{ .Values.sentry.customerName }}",
        "kots_channel": "{{ .Values.sentry.channelName }}",
        "kots_version": "{{ .Values.sentry.versionLabel }}"
      }
    }
  db.json: |
    {
      "generic": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}",
        "CAFile": "/etc/dozuki/rds-ca.pem"
      },
      "master": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}",
        "CAFile": "/etc/dozuki/rds-ca.pem"
      },
      "slave": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}",
        "CAFile": "/etc/dozuki/rds-ca.pem"
      },
      "sphinx": {
        "hostname": "{{ .Values.db.host }}",
        "user": "{{ .Values.db.user }}",
        "password": "{{ .Values.db.password }}",
        "CAFile": "/etc/dozuki/rds-ca.pem"
      }
    }
  frontegg.json: |
    {
      "clientId": "{{ .Values.frontegg.clientId }}",
      "apiToken": "{{ .Values.frontegg.apiToken }}",
      "apiBaseUrl": "http://frontegg-api-gateway.{{ .Release.Namespace }}.svc.cluster.local",
      "authUrl": "https://api.frontegg.com/auth/vendor"
    }
  surveyjs.json: |
    {
      "licenseKey": "{{ .Values.surveyjs.licenseKey }}"
    }
  rds-ca.pem: |
    {{ .Values.db.rdsCaCert | b64dec | nindent 4 }}
  google-translate.json: |
    {
      "apiToken": "{{ .Values.googleTranslate.token }}"
    }
  index.json: |
    {
      "index": {
        "legacy": {
          "filename": "legacy.json"
        },
        "s3": {
          "filename": "s3.json"
        },
        "buckets": {
          "filename": "buckets.json"
        },
        "db": {
          "filename": "db.json"
        },
        "memcached": {
          "filename": "memcached.json"
        },
        "aws-resources": {
          "filename": "aws-resources.json"
        }
      }
    }
  saml.json: |
    {
      "activeX509CertPath": "/var/www/key/tls.crt",
      "activePrivateKeyPath": "/var/www/key/tls.key",
      "pendingX509CertPath": "/var/www/key/tls.crt",
      "signatureAlgorithm": "RSA_SHA256"
    }
