apiVersion: v2
dependencies:
- name: api-gateway
  repository: https://frontegg.github.io/helm-charts/
  version: 0.4.38
- name: connectors-worker
  repository: https://frontegg.github.io/helm-charts/
  version: 0.1.23
- name: event-service
  repository: https://frontegg.github.io/helm-charts/
  version: 0.1.16
- name: integrations-service
  repository: https://frontegg.github.io/helm-charts/
  version: 0.1.9
- name: webhook-service
  repository: https://frontegg.github.io/helm-charts/
  version: 0.2.8
description: Frontegg's Connectivity Helm chart for Kubernetes
maintainers:
- email: guy@frontegg.com
  name: Guy Ludvig
name: connectivity
type: application
version: 0.2.1
