# -- Set frontegg's general configurations
# -- further configuration might be needed within a specific service
frontegg:
  ## -- Set frontegg's api url. Change in case Frontegg has provided a different url.
  apiUrl: "https://api.frontegg.com"

  # -- Set Docker Images registry properties
  images:
    # -- Set enabled to create a secret with Frontegg's registry properties
    enabled: true
    # -- Set registry name
    registry: docker.io
    # -- Set username for docker registry provided by Frontegg
    username: ""
    # -- Set password for docker registry provided by Frontegg
    password: ""


## -- api-gateway service is an entry point to Frontegg's connectivity.
api-gateway:
  # -- Provide the amount of pods if HPA is not enabled
  replicaCount: 2
  # -- Provide the image docker tag default: latest
  appVersion: "2021.5.4132030"
  # -- Manage docker image properties
  image:
    # -- Provide docker image repository
    repository: frontegg/hybrid-api-gateway
    # -- Provide image pull policy
    pullPolicy: IfNotPresent

  ## -- Set pod annotations
  podAnnotations: {}
  ## -- Set pod label
  podLabels: {}

  # -- Provide secret name for Frontegg's docker image repository.
  imagePullSecrets:
    - name: regcred

  # -- override application name instead of api-gateway for `app:` labels
  nameOverride: ""
  # -- Provide a name instead of {releaseName}-api-gateway
  fullnameOverride: ""

  # - Setup Service properties for api-gateway (open only one port)
  service:
    # -- Set service type
    type: ClusterIP
    # -- Set service port
    protocol: TCP
    # - Set service target port to map
    port: 80
    # -- Set port protocol default: TCP
    targetPort: 9090
    # - Set port name
    name: access-port

  # -- HPA properties for team-management-service
  # -- If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
  # -- If autoscaling is disabled team-management-service will be managed by replicaset with `replicaCount` determine pod amount
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75

  # -- Enable Ingress if access from the internet is needed
  ingress:
    enabled: false

    # -- provide a different name for the host path example: api.acme.com
    hostnameOverride: ""
    # -- provide the needed ingress annotation
    # -- example:
    # --  kubernetes.io/tls-acme: "true"
    # --  kubernetes.io/ingress.class: "nginx"
    # --  ingress.kubernetes.io/force-ssl-redirect: "true"
    # --  nginx.ingress.kubernetes.io/server-snippet: |
    # --    location ~* ^/(metrics|healthcheck) {
    # --      deny all;
    # --      return 403;
    # --    }
    annotations: {}
    # -- If enabled ingress will search for secret to enable TLS
    tls:
      enabled: false
      secretName: ""

  # -- Set api-gateway resources
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  ## Set nodeSelector, override in case your cluster node are labeled differently
  nodeSelector:
    "beta.kubernetes.io/os": linux

  # -- Provide deployment tolerations
  tolerations: []

  # -- Provide deployment affinity
  affinity: {}

  configuration:
    secrets: {}
    map: {}

  # -- Frontegg's services url for inner communications
  # -- Provide an alternate url for a service if a service name was changed
  network:
    adminsServiceUrl: http://frontegg-admins-service
    auditsServiceUrl: http://frontegg-audits-service
    authenticationServiceUrl: http://frontegg-authentication-service
    metadataServiceUrl: http://frontegg-metadata-service
    notificationServiceUrl: http://frontegg-notification-service
    reportsEngineUrl: http://frontegg-reporting-engine
    reportsServiceUrl: http://frontegg-reporting-service
    teamServiceUrl: http://frontegg-team-management-service
    vendorsServiceUrl: http://frontegg-vendors-service
    tenantsServiceUrl: http://frontegg-tenants-service
    webpushServiceUrl: http://frontegg-webpush-service
    featureFlagsServiceUrl: http://frontegg-feature-flags-service
    webhookServiceUrl: http://frontegg-webhook-service
    eventsServiceUrl: http://frontegg-event-service
    identityServiceUrl: http://frontegg-identity-service
    integrationsServiceUrl: http://frontegg-integrations-service

  # - Frontegg's api-gateway configuration properties
  frontegg:
    # Frontegg's authentication key, provided by Frontegg's integration team
    authenticationPublicKey: ""
    # Set Frontegg's managed api-gateway Url. Override only in case instructed by Frontegg.
    apiGatewayUrl: "https://api.frontegg.com"
    # Set Frontegg's managed authentication Url. Override only in case instructed by Frontegg.
    authenticationServiceUrl: "https://api.frontegg.com/auth/vendor"
    # Set Frontegg's managed configuration Url. Override only in case instructed by Frontegg.
    metadataServiceUrl: "https://api.frontegg.com/metadata"
    # Enable hybrid services by features, comma separated.
    # Supported types are: webhooks, event, integrations
    # Override only in case instructed by Frontegg
    hybridServices: "webhook,event,integrations"

# Connectors Worker service
connectors-worker:
  # Default values for events-service.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  ## Provide the amount of pods if HPA is not enabled
  ##
  replicaCount: 2

  ## Provide the image docker tag default: latest
  ##
  appVersion: "2021.5.5162227"

  ## Manage docker image properties
  ##
  image:
    ## Provide docker repository hub
    ##
    repository: frontegg/hybrid-connectors-worker
    ## Provide image pull policy
    ##
    pullPolicy: IfNotPresent

  ## Provide secret name for frontegg's repository
  ##
  imagePullSecrets:
    - name: regcred

  ## Provide a name in place of connectors-worker for `app:` labels
  ##
  nameOverride: ""
  ## Provide a name in place of {releaseName}-connectors-worker
  ##
  fullnameOverride: ""

  ## Setup Service properties for connectors-worker (open only one port)
  ##
  service:
    ## Set service type
    ##
    type: ClusterIP
    ## Set service port
    ##
    protocol: TCP
    ## Set service target port to map
    ##
    port: 80
    ## Set port protocol default: TCP
    ##
    targetPort: 3015
    ## Set port name
    ##
    name: http

  ## HPA properties for connectors-worker
  ## If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
  ## If autoscaling is disabled team-management-service will be managed by replicaset with `replicaCount` determine pod amount
  ##
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75

  ## Set connectors-worker resources
  ##
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  ## Set nodeSelector, override in case your cluster node are labeled differently
  nodeSelector:
    "beta.kubernetes.io/os": linux

  ## Provide deployment tolerations
  ##
  tolerations: []

  ## Provide deployment affinity
  ##
  affinity: {}

  configuration:
    secrets: {}
    map: {}

  # -- Connectors-worker uses kafka as a messageBroker (eventbus).
  #    Set Kafka's connections properties
  messageBroker:
    # -- Set kafka broker comma separated host urls
    #    Example: "acme.kafka1:9092, acme.kafka2:9092"
    brokerList: ""
    # -- Set kafka broker password if needed.
    #    Set empty string "" in case password is not needed.
    password: ""

  # -- Connectors-worker Redis properties
  redis:
    # -- Set Redis host url
    #    Example: acme.redis.com
    host: ""
    # -- Set Redis port, default is set 6379
    port: "6379"
    # -- Set Redis password
    password: ""
    # -- Set Redis database index, default value is 7. Alter if default value is already in use.
    index: "7"
    # -- Set rather if tls value (true|false) is enabled
    tls: "true"

  # -- Frontegg's Connectors-worker configuration properties
  frontegg:
    # -- Frontegg connectivity supports multiple channels.
    # -- available channels are email | sms | slack integration.
    # -- use comma separated values for example: email,slack,sms
    # -- Use an empty string "" for no channels selected
    channels: ""

    # Frontegg's connectivity uses twilio as a SMS Sender service.
    # If SMS messages are enabled set twilio configuration provided by Frontegg.
    twilio:
      # -- Set the sender phone number from your twilio account.
      sender: ""
      # -- Set the token number from your twilio account.
      token: ""
      # -- Set the accountId from your twilio account.
      accountId: ""

    # Frontegg's connectivity uses sendgrid or SES (Amazon) as email Sender service.
    # If Emails are enabled set configuration provided by Frontegg.
    emails:
      # -- Set the email supported provider [ses | sendgrid] default (sendgrid)
      provider: ""
      # -- Set your AWS SES properties (if enabled)
      aws:
        # - Set your AWS SES accessKey
        accessKey: ""
        # - Set your AWS SES secretAccess
        secretAccess: ""
        # - Set your AWS SES region
        region: ""
      # -- Set your Sendgrid properties (if enabled)
      sendgrid:
        # -- Set your Sendgrid apiKey
        apiKey: ""

# - Frontegg's event-service configuration properties
event-service:
  # Default values for events-service.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  ## Provide the amount of pods if HPA is not enabled
  ##
  replicaCount: 2

  ## Provide the image docker tag default: latest
  ##
  appVersion: "2021.5.5183929"

  ## Manage docker image properties
  ##
  image:
    ## Provide docker repository hub
    ##
    repository: frontegg/hybrid-event-service
    ## Provide image pull policy
    ##
    pullPolicy: IfNotPresent

  ## Provide secret name for frontegg's repository
  ##
  imagePullSecrets:
    - name: regcred

  ## Provide a name in place of event-service for `app:` labels
  ##
  nameOverride: ""
  ## Provide a name in place of {releaseName}-event-service
  ##
  fullnameOverride: ""

  ## Setup Service properties for event-service (open only one port)
  ##
  service:
    ## Set service type
    ##
    type: ClusterIP
    ## Set service port
    ##
    protocol: TCP
    ## Set service target port to map
    ##
    port: 80
    ## Set port protocol default: TCP
    ##
    targetPort: 3011
    ## Set port name
    ##
    name: http

  ## HPA properties for event-service
  ## If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
  ## If autoscaling is disabled team-management-service will be managed by replicaset with `replicaCount` determine pod amount
  ##
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75

  ## Set event-service resources
  ##
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  nodeSelector:
    "beta.kubernetes.io/os": linux

  ## Provide deployment tolerations
  ##
  tolerations: [ ]

  ## Provide deployment affinity
  ##
  affinity: { }

  configuration:
    secrets: { }
    map: { }

  # -- event-service uses MySql for consistency.
  #    For security reasons connectivity requires creating the "frontegg_events" schema in advance thus allowing the given database user not to be admin.
  database:
    # -- Set the database name, change only if the given name is taken for.
    name: frontegg_events
    # -- Set database host url
    host: ""
    # -- Set database username
    username: ""
    # -- Set database username password
    password: ""

  # -- event-service uses kafka as a messageBroker (eventbus).
  #    Set Kafka's connections properties
  messageBroker:
    # -- Set kafka broker comma separated host urls
    #    Example: "acme.kafka1:9092, acme.kafka2:9092"
    brokerList: ""
    # -- Set kafka broker password if needed.
    #    Set empty string "" in case password is not needed.
    password: ""

  # -- event-service Redis properties
  redis:
    # -- Set Redis host url
    #    Example: acme.redis.com
    host: ""
    # -- Set Redis port, default is set 6379
    port: "6379"
    # -- Set Redis password
    password: ""
    # -- Set Redis database index, default value is 7. Alter if default value is already in use.
    index: "7"
    # -- Set rather if tls value (true|false) is enabled
    tls: "true"

  # -- Frontegg's event-service configuration properties
  frontegg:
    # -- Set Frontegg's hybrid synchronization properties
    sync:
      # -- Enable or Disable Frontegg hybrid with Frontegg cloud.
      # -- By disabling this you might not see the changes on Frontegg portal or get updates.
      enabled: "true"
      # -- Set sync time interval with frontegg cloud in minutes
      timeInterval: "15"
    # -- Set frontegg authentication url. (by not setting value it will use frontegg's cloud url)
    authenticationUrl: ""
    # -- Set frontegg evnets Service url. (by not setting value it will use frontegg's cloud url)
    managedEventServiceUrl: ""
    # -- Set Your account client Id (provided in the portal administration page)
    clientId: ""
    # -- Set Your account Api Key (provided in the portal administration page)
    apiKey: ""
    # -- Set authentication failure retry delay in milliseconds
    authenticationRetryDelayInterval: "5000"
    # -- Set authentication failure behavior.
    # -- When authentication fails should the service stop?
    shutdownOnInitialAuthenticationFailure: "true"

# - Frontegg's webhook-service configuration properties
webhook-service:
  # -- Provide the amount of pods if HPA is not enabled
  replicaCount: 2

  # -- Provide the image docker tag default: latest
  appVersion: "2021.3.24161215"

  # -- Manage docker image properties
  image:
    # -- Provide docker repository hub
    repository: frontegg/hybrid-webhook-service
    # -- Provide image pull policy
    pullPolicy: IfNotPresent

  # -- Provide secret name for frontegg's repository
  imagePullSecrets:
    - name: regcred

  # -- Provide a name in place of webhook-service for `app:` labels
  nameOverride: ""
  # -- Provide a name in place of {releaseName}-webhook-service
  fullnameOverride: ""

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  # -- Setup Service properties for webhook-service (open only one port)
  service:
    # -- Set service type
    type: ClusterIP
    # -- Set service port
    protocol: TCP
    # -- Set service target port to map
    port: 80
    # -- Set port protocol default: TCP
    targetPort: 3013
    # -- Set port name
    name: http

  # -- Set webhook-service resources
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 1024Mi

  # -- HPA properties for webhook-service
  # -- If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
  # -- If autoscaling is disabled webhook-service will be managed by replicaset with `replicaCount` determine pod amount
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75

  nodeSelector:
    "beta.kubernetes.io/os": linux

  # -- Provide deployment tolerations
  tolerations: []

  affinity: {}

  configuration:
    secrets: {}
    map: {}
  # -- Webhook-service uses MongoDB for persistence
  #
  mongo:
    # -- Set MongoDB connection string (mongo://xxx@yyy/webhooks?)
    connectionString: ""
    # -- Set MongoDB connection retry attempts
    retryAttempts: "3"
    # -- Set MongoDB connection retry attempts delay in milliseconds
    retryDelay: "1000"

  # -- webhook-service uses kafka as a messageBroker (eventbus).
  #    Set Kafka's connections properties
  messageBroker:
    # -- Set kafka broker comma separated host urls
    #    Example: "acme.kafka1:9092, acme.kafka2:9092"
    brokerList: ""
    # -- Set kafka broker password if needed.
    #    Set empty string "" in case password is not needed.
    password: ""
    # -- Set kafka broker topic. Override only in case current name is taken for.
    topic: "events"

  # -- webhook-service uses MySql for consistency.
  #    For security reasons connectivity requires creating the "frontegg_webhooks" schema in advance thus allowing the given database user not to be admin.
  mysql:
    # -- Set the database name, change only if the given name is taken for.
    name: frontegg_webhooks
    # -- Set database host url
    host: ""
    # -- Set database username
    username: ""
    # -- Set database username password
    password: ""

integrations-service:
  # Default values for integrations-service.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # -- Provide the amount of pods if HPA is not enabled
  replicaCount: 2

  # -- Provide the image docker tag default: latest
  appVersion: "2021.5.5162332"

  # -- Manage docker image properties
  image:
    # -- Provide docker repository hub
    repository: frontegg/hybrid-integrations-service
    # -- Provide image pull policy
    pullPolicy: IfNotPresent

  # -- Provide secret name for frontegg's repository
  imagePullSecrets:
    - name: regcred

  # -- Provide a name in place of integrations-service for `app:` labels
  nameOverride: ""
  # -- Provide a name in place of {releaseName}-integrations-service
  fullnameOverride: ""

  # -- Setup Service properties for integrations-service (open only one port)
  service:
    # -- Set service type
    type: ClusterIP
    # -- Set service port
    protocol: TCP
    # -- Set service target port to map
    port: 80
    # -- Set port protocol default: TCP
    targetPort: 3014
    # -- Set port name
    name: http

  # -- HPA properties for integrations-service
  # -- If autoscaling is enabled it will monitor the service and raise or lower pods amount based upon usage
  # -- If autoscaling is disabled integrations-service will be managed by replicaset with `replicaCount` determine pod amount
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75

  # -- Set integrations-service resources
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi

  nodeSelector:
    "beta.kubernetes.io/os": linux

  # -- Provide deployment tolerations
  tolerations: [ ]

  # -- Provide deployment affinity
  affinity: { }

  configuration:
    secrets: { }
    map: { }

  # -- integrations-service uses MongoDB for persistence
  #
  mongo:
    # -- Set MongoDB connection string (mongo://xxx@yyy/integrations?)
    connectionString: ""


  # -- integrations-service uses kafka as a messageBroker (eventbus).
  #    Set Kafka's connections properties
  messageBroker:
    # -- Set kafka broker comma separated host urls
    #    Example: "acme.kafka1:9092, acme.kafka2:9092"
    brokerList: ""
    # -- Set kafka broker password if needed.
    #    Set empty string "" in case password is not needed.
    password: ""

  # - Set integrations service Frontegg properties
  frontegg:
    # slack integration service requires slack encryption key
    slack:
      # -- Set Slack encryption key provided by Frontegg
      encryptionKey: ""
