apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: {{ .Values.deployments.app.name }}
spec:
  replicas: {{ .Values.deployments.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployments.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.app.name }}
    spec:
      hostAliases:
        {{- range .Values.hostAliases }}
        - ip: {{ .ip }}
          hostnames:
            {{- range .hostnames }}
            - {{ . }}
            {{- end }}
        {{- end }}
      containers:
        - name: {{ .Values.deployments.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- range .Values.deployments.app.command }}
            - "{{ . }}"
            {{- end }}
          env:
            {{- range .Values.deployments.app.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: USER_USERHOSTNAME
              value: {{ .Values.hostname | quote }}
            - name: K8_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            {{- range .Values.deployments.app.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.deployments.app.resources.requests.cpu }}
              memory: {{ .Values.deployments.app.resources.requests.memory }}
          ports:
            {{- range .Values.deployments.app.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          livenessProbe:
                  {{- if .Values.deployments.app.livenessProbe }}
                  {{- with .Values.deployments.app.livenessProbe }}
                  {{ toYaml . | indent 8 }}
                  {{- end }}
                  {{- end }}
          readinessProbe:
                  {{- if .Values.deployments.app.readinessProbe }}
                  {{- with .Values.deployments.app.readinessProbe }}
                  {{ toYaml . | indent 8 }}
                  {{- end }}
                  {{- end }}
      volumes:
        {{- range .Values.deployments.app.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap }}
          {{- else if .secret }}
          secret:
            secretName: {{ .secret }}
          {{- end }}
        {{- end }}
      restartPolicy: Always
      initContainers:
        {{- range .Values.deployments.app.initContainers }}
        - name: {{ .name }}
          image: {{ .image }}
          command:
            {{- range .command }}
            - {{ . }}
            {{- end }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          volumeMounts:
            {{- range .volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .resources.requests.cpu }}
              memory: {{ .resources.requests.memory }}
        {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.deployments.app.name }}
                topologyKey: "kubernetes.io/hostname"
