{{- /* Helm template for searchd deployment */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-searchd-deployment
  annotations:
    reloader.stakater.com/auto: "true"
    kots.io/config-hash: "{{ .Values.deployments.app.configHash }}"
  labels:
    app: {{ .Values.deployments.searchd.name }}
spec:
  replicas: {{ .Values.deployments.searchd.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployments.searchd.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.searchd.name }}
    spec:
      hostAliases:
        {{- range .Values.hostAliases }}
        - ip: {{ .ip }}
          hostnames:
            {{- range .hostnames }}
            - {{ . }}
            {{- end }}
        {{- end }}
      containers:
        - name: {{ .Values.deployments.searchd.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- range .Values.deployments.searchd.command }}
            - "{{ . }}"
            {{- end }}
          env:
            - name: USER_USERHOSTNAME
              value: {{ .Values.hostname | quote }}
            - name: K8_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            {{- range .Values.deployments.searchd.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.deployments.searchd.resources.requests.cpu }}
              memory: {{ .Values.deployments.searchd.resources.requests.memory }}
          ports:
            {{- range .Values.deployments.searchd.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
      volumes:
        {{- range .Values.deployments.searchd.volumes }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap }}
        {{- end }}
      restartPolicy: {{ .Values.deployments.searchd.restartPolicy }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.deployments.searchd.name }}
                topologyKey: "kubernetes.io/hostname"
