apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connectors-worker.fullname" . }}-secret
  labels:
  {{- include "connectors-worker.labels" . | nindent 4 }}
data:
  {{- with .Values.messageBroker }}
  FRONTEGG_KAFKA_SLACK_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_SLACK_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_KAFKA_EMAIL_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_EMAIL_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_KAFKA_SMS_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote  }}
  FRONTEGG_KAFKA_SMS_SASL_PASSWORD: {{ .password | b64enc | quote }}
  FRONTEGG_KAFKA_EVENTS_STATUS_BROKER_LIST: {{ required "A valid .Values.messageBroker.brokerList entry required!" .brokerList | b64enc | quote }}
  FRONTEGG_KAFKA_EVENTS_STATUS_SASL_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.redis }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_HOST: {{ required "A valid .Values.redis.host entry required!" .host | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PORT: {{ required "A valid .Values.redis.port entry required!" .port | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_DB_INDEX: {{ required "A valid .Values.redis.index entry required!" .index | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_TLS: {{ required "A valid .Values.redis.tls entry required!" .tls | b64enc | quote }}
  FRONTEGG_CONNECTORS_WORKER_SERVICE_REDIS_PASSWORD: {{ .password | b64enc | quote }}
  {{- end }}
  {{- with .Values.frontegg }}
  FRONTEGG_CHANNELS_TO_RUN: {{ required "A valid .Values.frontegg.channels entry required!" .channels | b64enc | quote }}
  {{- with .twilio }}
  FRONTEGG_TWILIO_SENDER: {{ .sender | b64enc | quote }}
  FRONTEGG_TWILIO_TOKEN: {{ .token | b64enc | quote }}
  FRONTEGG_TWILIO_ACCOUNTSID: {{ .accountId | b64enc | quote }}
  {{- end }}
  {{- with .emails}}
  FRONTEGG_EMAIL_PROVIDER: {{ .provider | b64enc | quote }}
  {{- with .aws}}
  FRONTEGG_AWS_ACCESS_KEY_ID: {{ .accessKey | b64enc | quote }}
  FRONTEGG_AWS_SECRET_ACCESS_KEY: {{ .secretAccess | b64enc | quote }}
  FRONTEGG_AWS_REGION: {{ .region | b64enc | quote }}
  {{- end }}
  {{- with .sendgrid }}
  FRONTEGG_SENDGRID_API_KEY: {{ .apiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

