apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: primary
spec:
  resyncPeriod: "24h"
  instanceSelector:
    matchLabels:
      dashboards: "grafana-primary"
  datasource:
    name: MySQL
    type: mysql
    access: direct
    user: dozuki
    database: onprem_guide
    url: '{{ .Values.db.host }}:3306'
    isDefault: true
    secureJsonData:
      password: '{{ .Values.db.password }}'
    jsonData:
      'timeInterval': "5s"
    editable: false