apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "integrations-service.fullname" . }}-deployment
  labels:
  {{- include "integrations-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "integrations-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.frontegg.com/appVersion: {{ .Values.appVersion }}
      {{- include "integrations-service.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ (print .Values.secret) | sha256sum }}
        checksum/config: {{ (print .Values.configmap) | sha256sum }}
        checksum/template.config-map: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
        checksum/template.secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.appVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            {{- range $secret_name, $values := .Values.configuration.secrets }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret_name }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
            {{- range $config_name, $values := .Values.configuration.map }}
            {{- range $key, $value :=  $values}}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config_name }}
                  key: {{ $value }}
          {{- end }}
          {{- end }}
#          volumeMounts:
#            - name: mongo-tls-ca
#              mountPath: "/etc/rds-combined-ca-bundle.pem"
#              subPath: "rds-combined-ca-bundle.pem"
          envFrom:
            - configMapRef:
                name: {{ include "integrations-service.fullname" . }}-configmap
            - secretRef:
                name: {{ include "integrations-service.fullname" . }}-secret

          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
#      volumes:
#        - name: mongo-tls-ca
#          configMap:
#            name: mongo-tls
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
